name: DevSecOps workflow for the lab

run-name: DevSecOps lab workflow starded by ${{github.actor}}

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  php-sca-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v3

      - name: Install PHP dependencies
        run: cd ./vulnerabilities/api/ |
         composer install

      - name: Run Composer audit
        run: composer audit
